# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/user.proto", :syntax => :proto3) do
    add_message "user.GetUserRequest" do
      optional :id, :int64, 1
    end
    add_message "user.GetUserResponse" do
      optional :id, :int64, 1
      optional :name, :string, 2
      optional :mail, :string, 3
      optional :gender, :enum, 4, "user.Gender"
      optional :affiliation, :enum, 5, "user.Affiliation"
      repeated :groups, :message, 6, "user.Group"
      repeated :skills, :message, 7, "user.Skill"
    end
    add_message "user.Group" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :description, :string, 3
    end
    add_message "user.Skill" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :level, :int32, 4
    end
    add_enum "user.Gender" do
      value :MAN, 0
      value :WOMAN, 1
      value :GENDER_OTHER, 2
    end
    add_enum "user.Affiliation" do
      value :STUDENT, 0
      value :AFFILIATION_OTHER, 1
    end
  end
end

module User
  GetUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.GetUserRequest").msgclass
  GetUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.GetUserResponse").msgclass
  Group = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Group").msgclass
  Skill = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Skill").msgclass
  Gender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Gender").enummodule
  Affiliation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Affiliation").enummodule
end
